/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;


import cenafilosofos.Filosofo;
import cenafilosofos.mesa;
import java.awt.Image;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alexa
 */
public class cenaVisual extends javax.swing.JFrame {
    //variable para iniciar o detener el hilo de lo visual
    boolean iniciar = false;
    
    //inicializamos una mesa que tiene 5 tenedores
    mesa mesa = new mesa(5);
    Filosofo[] filosofos=new Filosofo[5];
    

    
    /**
     * Creates new form cenaVisual
     */
    
    
    public cenaVisual() {
        initComponents();
        mesaImg.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("mesa.png")).getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH)));
        filosofo1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("filosofo.png")).getImage().getScaledInstance(96, 108, Image.SCALE_SMOOTH)));
        filosofo2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("filosofo.png")).getImage().getScaledInstance(96, 108, Image.SCALE_SMOOTH)));
        filosofo3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("filosofo.png")).getImage().getScaledInstance(96, 108, Image.SCALE_SMOOTH)));
        filosofo4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("filosofo.png")).getImage().getScaledInstance(96, 108, Image.SCALE_SMOOTH)));
        filosofo5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("filosofo.png")).getImage().getScaledInstance(96, 108, Image.SCALE_SMOOTH)));
        accion1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("pensando.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
        accion2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("pensando.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
        accion3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("pensando.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
        accion4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("pensando.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
        accion5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("pensando.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesaImg = new javax.swing.JLabel();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo5 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();
        accion2 = new javax.swing.JLabel();
        accion3 = new javax.swing.JLabel();
        accion1 = new javax.swing.JLabel();
        accion5 = new javax.swing.JLabel();
        accion4 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mesaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/mesa.png"))); // NOI18N

        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/filosofo.png"))); // NOI18N
        filosofo1.setText("Filosofo1");

        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/filosofo.png"))); // NOI18N
        filosofo2.setText("Filosofo2");

        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/filosofo.png"))); // NOI18N
        filosofo3.setText("Filosofo3");

        filosofo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/filosofo.png"))); // NOI18N
        filosofo5.setText("Filosofo5");

        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/filosofo.png"))); // NOI18N
        filosofo4.setText("Filosofo4");

        accion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/pensando.png"))); // NOI18N
        accion2.setText("pensando1");

        accion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/pensando.png"))); // NOI18N
        accion3.setText("pensando1");

        accion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/pensando.png"))); // NOI18N
        accion1.setText("pensando1");

        accion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/pensando.png"))); // NOI18N
        accion5.setText("pensando1");

        accion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/pensando.png"))); // NOI18N
        accion4.setText("pensando1");

        titulo.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        titulo.setText("Cena de los Filósofos");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnParar.setText("Detener");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(675, Short.MAX_VALUE)
                                .addComponent(accion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnParar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accion2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filosofo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filosofo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mesaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(filosofo5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filosofo4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filosofo1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(accion5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(accion4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(925, Short.MAX_VALUE)
                    .addComponent(accion1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(510, 510, 510)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(filosofo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(mesaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(accion5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(filosofo5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(filosofo4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(accion4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(titulo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accion2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filosofo2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(filosofo3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(accion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnParar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(accion1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(708, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        boolean primeraVez=false;
        
        //para inicializar el hilo
        iniciar=true;
        
        if(primeraVez==false){
            primeraVez=true;
            //empezar 5 hilos, cada uno de ellos emula a un filosofo
            for (int i = 1; i <= 5; i++) {
                filosofos[i-1] = new Filosofo(mesa, i);
                filosofos[i-1].start();
            }  
        
        }
        
         Thread uiUpdateThread = new Thread(() -> {
            while (iniciar) {
                // Actualizar la interfaz gráfica en el hilo de la UI
                SwingUtilities.invokeLater(() -> updateUI(filosofos));

                try {
                    Thread.sleep(100); // Esperar antes de actualizar nuevamente
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        uiUpdateThread.start();
    

        
       

        

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        iniciar=false;
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    
private void updateUI(Filosofo[] filosofos) {
    for (int i = 0; i < filosofos.length; i++) {
        Filosofo filosofo = filosofos[i];
        JLabel accionLabel = getAccionLabel(i + 1); // Obtener el JLabel correspondiente al filósofo

        if (filosofo.isEstaComiendo()) {
            // Cambiar la imagen en el JLabel para el filósofo que está comiendo
            accionLabel.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("comiendo.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
        } else {
            // Cambiar la imagen en el JLabel para el filósofo que está pensando
            accionLabel.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("pensando.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));
        }
    }
}

private JLabel getAccionLabel(int filosofoId) {
    switch (filosofoId) {
        case 1:
            return accion1;
        case 2:
            return accion2;
        case 3:
            return accion3;
        case 4:
            return accion4;
        case 5:
            return accion5;
        default:
            return null;
    }
}

    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cenaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cenaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cenaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cenaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cenaVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accion1;
    private javax.swing.JLabel accion2;
    private javax.swing.JLabel accion3;
    private javax.swing.JLabel accion4;
    private javax.swing.JLabel accion5;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JLabel filosofo5;
    private javax.swing.JLabel mesaImg;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
